### ISSUE TITLE
Thoughts on passing meta property from action to requestInstance?

### ISSUE THREAD

**Issue by defdata** [klis87/redux-saga-requests#123]
I'm writing a driver that allows you to attach json schema definitions to the request payload and it returns mock data as a means to create a mock api layer using redux-saga-requests. I have a pretty raw working example, but I'm currently putting the schema definition in the request payload and I feel like it should be in the meta property and should not be part of the request. Based on this line:

https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas.js#L114

It looks like the meta property is not being passed in, but it seems like it could be... thoughts? Additionally it could also be done in a more flexible way where you could define what keys of an action payload you want passed. Implementation is a but fuzzier for me on that approach though.

Also is there any disadvantage do you think to passing around a schema definition with the payload? I was also considering registering schemas during initialization of the instance and looking them up with a key from the action payload instead. Anyways, awesome job on the lib. I was basically writing something similar at work to deal with the boilerplate from sagas, but your solution is more refined and further along.

**Comment by klis87** [comment]
Thanks for kind words :)

Regarding your issue, I think that `registering schemas during initialization of the instance` as your alternative solution is clearly better, because then action object wont contain this information, and later you could just replace mock driver with `axios` for instance and you wont even need to change your application code.

Actually such a mocking driver is on my todo list, and your post just shows this is really needed. Several ideas on my list regarding this topic:
- adding support for multiple drivers - 1 would be default, which could be overwritten in `request.driver` key per action if desired
- implementing mocking driver, which could be used for tests or for mocking when an api endpoint is not ready yet for example, this will be especially handy with multiple driver support, there wont be any need to wait for backend dev to prepare sth or to mock those things in a way which will require later refactoring, you would be able to just replace driver from mocking one and thats it

**Comment by defdata** [comment]
I like the idea of multiple drivers a lot as a way of switching drivers during runtime. I started working on the mocking driver for the exact reasons you listed, our UI and API teams are on different feature development schedules and the UI needs to be able to selectively have certain endpoints mocked out. I think having a way to automatically switch all endpoints to be mocked could also be useful, let's say you had to demo something and the api was down for example.

I'll refactor what I have later this week to register the schemas upon initialization of the mock client which I agree is a better solution. I need to be able to associate the action or request with a schema during that initialization. I'm thinking either by actionType or by the request route... If I do the request route I'd have to add some type of pattern matching to associate routes with variable params, not super wild about that, so actionType seems like it might be the way to go here. Anyways, would love to contribute, let me know if you need any help on anything, I've been digging through the code a bit.

**Comment by klis87** [comment]
I think that action type as a key is definitely the way to go, it is unique after all, contrary to url especially in restful api, where u have http method as well.

Thanks for your offer, I have many stuff on my todo list, if anything comes up, I will make an issue and any PR is welcome!

I plan to do a similar driver on my own for mocking, because I wouldnt use JSON schema for it, just simple objects, but once you finish it, we could add it to the project readme as an external community package

**Comment by defdata** [comment]
Awesome thanks! I'll close this issue and let u know when it is ready. Thanks!

**Comment by klis87** [comment]
@defdata After rethinking this, I think that `url` + `method` would be a better indentifier. For 1 thing, the whole action is not passed to driver, only request config. Also, the closer request config will look like for mocking driver and axios/fetch driver, the better.
