### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Verurteilt** [klis87/redux-saga-requests#157]
When trying to use the library it crashes with the next error:

```
ReferenceError: regeneratorRuntime is not defined
./node_modules/redux-saga-requests/es/sagas.js
node_modules/redux-saga-requests/es/sagas.js:3
  1 | var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
  2 | 
> 3 | var _marked = /*#__PURE__*/regeneratorRuntime.mark(getRequestInstance),
  4 |     _marked2 = /*#__PURE__*/regeneratorRuntime.mark(sendRequest),
  5 |     _marked3 = /*#__PURE__*/regeneratorRuntime.mark(cancelSendRequestOnAction),
  6 |     _marked4 = /*#__PURE__*/regeneratorRuntime.mark(watchRequests);
View compiled
__webpack_require__
/opt/frontend/webpack/bootstrap 565f41d7711f2490b577:707
```

**Comment by klis87** [comment]
@Verurteilt This is because `redux-saga` uses generator which is not supported in all browsers. Hence Babel uses so called `regeneratorRuntime` generator transform, which requires polyfill. The easiest way to solve this is to install `babel-polyfill` and import it before all imports:
`import 'babel-polyfill';`

See https://github.com/klis87/redux-saga-requests/tree/master/examples/basic example for more info.

**Comment by klis87** [comment]
@Verurteilt I added `@babel/runtime` to dependencies, so if your browsers or NodeJS support ES6 generators, you don't need to use `babel-polyfill` anymore.
