### ISSUE TITLE
Actions with parameters, multiple states

### ISSUE THREAD

**Issue by jleck** [klis87/redux-saga-requests#165]
Hi,

I'm having a play to see to see if we can use this where I work.

How would you handle multiple calls using the same action? For example:

```
getPost(1);
getPost(2);
```

Redux override post 1 with post 2, whereas I need both. Is there any provision for that?

**Comment by klis87** [comment]
@jleck it is because by default I use redux saga `takeLatest` effect as usually we are only interested in the last result to avoid race conditions. However, you can override this behavior globally or per action. See https://github.com/klis87/redux-saga-requests#watchrequests docs

so in your case:
```js
yield watchRequests(
  null,
  {
    GET_POST: { takeLatest: false }
  }
);
```
should be all you need.

In the future I will allow overriding by adding `meta.takeLatest` to a give request action itself.

**Comment by jleck** [comment]
@klis87 ah, yes I saw that option. The problem I have is the standard reducer only going able to store one response per action. e.g.:

```
getPost(1);
getPost(2);
```

Both store in the reducer as post, so I can’t use them both at the same time. I could build a custom reducer, but I would imagine this is a pretty popular pattern. Maybe there could be an additional type of request reducer used to support actions with parameters.

Everything else is working swimmingly though :)

**Comment by klis87** [comment]
@jleck yeah I know, `requestsReducer` doesnt cover this case. But frankly, I need more info as I never used such a pattern, I either have lists API endpoints or detailed, and if I need more than 1, I just fetch lists.

Could you  tell me more about your use case, why you fetch posts 1 by 1 and in what context?

We could think of introducing an additional option to `requestsReducer` to allow such pattern, but I have many todos for this project which are important for my app projects, so I wont be able to work on this quite soon, but I will happily accept PR :)

I am glad the rest fits your project :)

**Comment by jleck** [comment]
A good example would related posts under under a main post. If the main post returned the IDs of two related posts as part of their data. I might have the following actions:

getPostSummary(1);
getPostSummary(2);

Or something like that. I'm just finishing off a pretty large react app and we often call the same API with different IDs within the same route.

**Comment by klis87** [comment]
@jleck alternative solution would be to prepare rest api endpoint like `/api/main-posts/1/related-posts/`.

However, I came up with quite interesting solution for you! You can use batch requests:
```js
const getPostSummaries = (postsIds) => ({
  type: 'GET_POST_SUMMARIES',
  request: postsIds.map(id => ({ url: `/post-summary/${id}` })),
});
```

It should work, and your `requestReducer` should get array of responses. Pls let me know if that is a good solution for you.

**Comment by klis87** [comment]
BTW, dont use `takeLatest: false` then, because I guess you are only interested with last bulk of post summaries, and if you switch your route, you will fetch a new bulk. Advantage is that if you do  `getPostSummaries([1, 2, 3])` and soon `getPostSummaries([4, 5])`, you are guaranteed to avoid any race condition issues, because then 3 requests from `getPostSummaries([1, 2, 3])` would be aborted if still pending during `getPostSummaries([4, 5])` execution.

**Comment by jleck** [comment]
Hmm, ideally your endpoint would be available, but we don't always have control over the endpoints.

The problem with your example is that I might have a component called relatedPost which I use twice. In theory I could run your batch higher up and pass it as props, but then it has a dependency on something else, rather than just being able to pass the ID as a prop.

**Comment by klis87** [comment]
@jleck If think it would be beneficial to indeed create wrapper for you `relatedPost` components and call `getPostSummaries` from it, or actually in route component you could do that too. It is just a safer solution than adjusting `requestReducer` to allow keeping multiple objects. Just think that you could download hunders of posts this way which would just populate more and more memory, or you would need to clean them manually. Also, performance would be greated too because the more redux actions you have, the worse.

**Comment by klis87** [comment]
and regarding dependency, you still can create dedicated redux selector to get post by id, so you dont need to inject more into your `relatedPost` even with my solution

**Comment by klis87** [comment]
Closing as I really think that this use cases is really well handled by suggestions in this topic. If anyone has some related issues or problematic use cases, pls let me know in this issue or a new one.

**Comment by klis87** [comment]
@jleck this is now supported with request action `meta.requestKey`
