### ISSUE TITLE
Is it possible to remove axios dependency from redux-saga-requests-fetch

### ISSUE THREAD

**Issue by vomchik** [klis87/redux-saga-requests#228]
Is it possible to remove axios dependency?
https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-fetch/src/fetch-api-driver.js#L1

**Comment by klis87** [comment]
it would be, but `isAbsoluteUrl` it surprisingly complex and I didn't want to worry about it myself if I could rely on mature mainained library.

Is there any specific reason you want it to removed? It won't affect your bundlesize because only this specific axios function is imported, we don't have whole axios overhead

**Comment by vomchik** [comment]
> Is there any specific reason you want it to removed? It won't affect your bundlesize because only this specific axios function is imported, we don't have whole axios overhead

Yes, it was the main reason. Thanks for the explanation.
