### ISSUE TITLE
Cache based on params

### ISSUE THREAD

**Issue by megawac** [klis87/redux-saga-requests#232]
In my use case I am fetching many resources based on some parameter, `mapId`. I'd like to cache the responses of the actions based on the url rather than the action type.

For example, I have an action `getFeatures` that fetches a url with a 2 hour cache. Despite the url changing based on a passed in parameter which will alter the response the existing `CacheMiddleware` will not respect this as a different request.

```js
const getFeatures = createAction(`get features`, ({ mapId }) => {
  return {
    request: {
      url: `/v2/maps/features/?map=${mapId}`
    },
    meta: {
      cache: 7200, // 2 hours
    }
  };
});
```

**Comment by megawac** [comment]
I'm planning to create an `IndexedDB` based cache middleware at some point so its not the end of the world that the libraries provided caching middleware doesn't work for my use case, I just wanted to raise this concern.

**Comment by klis87** [comment]
Funny, because I need to extend caching too, but I am not sure my use case is the same as yours. Mine is the following:

I have many endpoints requiring some kind of context, like organizationId. Like you mentioned, current caching solution isnt compatible, because on organizatonId change, new requests will be ignored. I am going to add new `action.meta.cacheKey` (instead of caching by url, because then it woudln't be compatible with graphql, also some people could use request header/query string, so `cacheKey` would be the most flexible)

so lets say I have action like:
```js
fetchBooks = organizationId => ({
  request: {
    url: `/books?organizationId=${organizationId}`
  },
  meta: {
    cache: 7200,
    cacheKey: organizationId, // change will invalidate the cache
  }
})
```

Now, lets say we dispatch following actions, with commented results:
- `fetchBooks(1)` // triggers request
- `fetchBooks(1)` // ignores request, cache HIT
- `fetchBooks(1)` // ignores request, cache HIT
- `fetchBooks(2)` // triggers request, cache gets invalidated as `cacheKey` changed
- `fetchBooks(2)` // ignores request, cache HIT
- `fetchBooks(1)` // triggers request, cache gets invalidated as `cacheKey` changed

The only downside with this solution is that u cannot cache more that one response at the same time, so in above case caching books with organizationId 1 and 2, so on `cacheKey` we would still have cache hit. This is because current cache solution actually doesnt have any response copies, state is kept in reducer without any change, just Redux actions for cached requests are ignored. I did it because it was the easiest plus you dont spam redux store with redundant requests actions.

So, does it meet your use case, or you are not interested only in caching the last `mapId`?

Btw, out of curiosity, does `createAction` comes from `redux-act`? if yes, I am not sure this would work, rather this:
```js
const getFeatures = createAction(`get features`, ({ mapId }) => {
  return {
    request: {
      url: `/v2/maps/features/?map=${mapId}`
    },
  };
}, () => ({
 cache: 7200, // 2 hours
}));
```
But probably you use a different action creator library :)

**Comment by megawac** [comment]
Yeah, you're right :D. I was just trying to provide an example of what wouldn't work with the current implementation.

I like the idea of the cache key, but as for the cache middleware only storing 1 response, would it be possible to instead make it configurable. In my case I'd prefer to cache the last 2 or 3 responses as its going to be a common use case to switch between maps.

If you implement the `cacheKey` part I'll probably fork your cache middleware or provide a follow-up pr that adds support for caching the last `n` items if you're interested in that feature.

**Comment by klis87** [comment]
The problem is that allowing to store more than last 1 response would require a complete different caching approach. Current solution just checks whether we should use the cache, and cache middleware ignores a given request action. This is also compatible with using `sendRequest`, because cache middleware returns null when cache hit. This info is used here by `sendRequest` - https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas.js#L88

However, supporting more than 1 response per request type would require to always dispatch request and response actions, because reducers data has to be replaced when updating data from cache with a different `cacheKey`. It turnes out it is not possible (at least I dont see how) to implement multiple responses inside middleware. It would work for dispatching request actions, but it wouldn't if someone used `sendRequest`. So, to support this feature, we would need to remove cacheMiddleware and move caching behaviour to `sendRequest` itself. Now, we have to decide whether this feature is really needed. I guess that it is, and if I dont miss anything, caching has to be completely  rewritten now.

**Comment by klis87** [comment]
Actually I figured it out, we just need extra action.meta.cacheHit flag, which will be appended by middleware, thats enough to communicate with sendRequest. We could use it also in requestsReducer not to increment pending counter on request with cache hit.

**Comment by megawac** [comment]
Now that I've had some more time to look into it, I think in retrospect I will likely be simply using a `ServiceWorker` to do my request caching.

**Comment by klis87** [comment]
Nice idea too. I am just wondering, whether it will be clean and easy to implement on `ServiceWorker` level.

**Comment by megawac** [comment]
I'm hoping it will be similar to this example: https://jakearchibald.com/2014/offline-cookbook/#cache-falling-back-to-network

**Comment by klis87** [comment]
Nice. However, I think that this library should have 1st caching support anyway, because with service worker you need to manage it yourself plus you need to sync urls between service workers and redux actions.

I really want caching multiple resources built in in this libary, with ability to set `cacheSize` in `action.meta` so users could control its size.

I am not sure when I will have time to do it though, hopefully sooner than later. I will let you know once done. Good you have alternative as well, so you won't be blocked.

**Comment by klis87** [comment]
@megawac I am not sure whether you will stick to service worker caching, but I pushed caching per key in latest `0.34.0` version.

**Comment by megawac** [comment]
Cool, yeah I’m still debating my approach. Right now I have memory caching
in place which I implemented via an interceptor saga. I have been debating
going with a indexeddb or a service worker approach going forward. I
prototyped the service worker and it was easy to get going but less
flexible
