### ISSUE TITLE
[Idea] byId Reducer For Direct Object Access

### ISSUE THREAD

**Issue by Flash619** [klis87/redux-saga-requests#234]
Currently it looks like the `all` reducer stores objects as an array. You could convert it with something like the following.

```javascript
const arrayToObject = (array, key) => array.reduce((result, val, inx) => {
  result[val[key]] = val
  return result
}, {})

const myObjectsById = arrayToObject(myObjects, 'id')
```

However this adds overhead for every component that may directly access these values via connect or any other property sharing mechanism. Currently, I do not use the pre-built reducers included with redux-saga-requests, mostly in part because I can't find a way to directly access objects by id. Typically I run an all reducer right next to a `byId` reducer. While this results in twice the storage being used, I feel it adds more efficiency to my code base by allowing direct es5 based iteration over the all reducer, and direct access to objects with the `byId` reducer. 

I was just curious, are there any plans to add this feature in the future? I've implemented this library in several projects so far and love everything it seems to offer, this is the only limitation I've found so far even though its very easy to work around and is not necessary.

**Comment by klis87** [comment]
Currently reducers store data in the exact shape like returned from the server. So if your server responds with array with big amount of nodes, this is what reducer will keep. You can control the exact shape in `requestsReducer` by implementing `getData` callback, you could for example call your `arrayToObject` function there. This callback would be executed only once per request, so not often. Alternatively, if you want your reducers to have original response, but also you would like to have data grouped by id, you can use write selectors with `reselect`, so again, it will be executed only once per request due to memoizing. Also, if you need it, you can configure `multiple` or `getDefaultData` to control reducers initial `data`.

Do you think it is enough for your use case?

**Comment by Flash619** [comment]
Late reply... So what if, for instance, I use the onSuccess saga, then in the onSuccess saga mutate the action prior to being dispatched to the reducers by running the response through normalizr. As normalizr returns an object with IDs as indexes, would the reducer have any issue with that? I guess I haven't tried this yet.

**Comment by klis87** [comment]
Reducers don't care about object structure of `data`, so it shouldn't cause any issues.

**Comment by klis87** [comment]
Closing, this can be solved with `getData` or a custom selector. In the future versions it is possible that I will implement some automatic normalization of data with automatic getById selectors.
