### ISSUE TITLE
Should onSuccess interceptor fire if a request is aborted?

### ISSUE THREAD

**Issue by spacesuitdiver** [klis87/redux-saga-requests#241]
I'm seeing this behavior, sorry if it's apparent that it should somewhere in the docs.

**Comment by klis87** [comment]
It should not. Generally for each request always `onRequest` interceptor is fired, and then either `onSuccess`, `onError` or `onAbort`.

If you see a different behaviour, my guesses are:
- you abort a request after already received response
- you fired another request of the same type before previous was finished, so according to default takeLatest policy, previous one will be aborted, and second one will succeed, so for 1st request `onAbort` would be fired, for 2nd one `onSuccess`

If I didn't hit and you see `onSuccess` in another scenario, please describe it.

**Comment by spacesuitdiver** [comment]
I think I have a separate issue which I will describe below. Regarding the issue at hand I guess I'm falling under the first bullet. What I see logged is **three** `onSuccess` executions but in redux inspector I see only **two** success actions `AUTH_SUCCESS` and `FETCH_RESOURCES_SUCCESS` and a handful of `FETCH_RESOURCES_ABORT` which is concerning to me because I would think I should see them match up at least.

What I'm trying to do and have so far is:
`onSuccess` which if the authorization token in response changes fires a `TOKEN_UPDATED` action which I can create watchers to listen for. Next I've made a watcher to listen for `TOKEN_UPDATED` and fire `FETCH_RESOURCES`. Since API always generates a new authorization key we end up with an infinite loop unless we are able to get a response back fast enough to have two authorization tokens match as `FETCH_RESOURCE` would continue to fire `TOKEN_UPDATED` via `onSuccess` continuously.

**Comment by klis87** [comment]
I would really need a repository reproducing this issue, otherwise it is hard for me to help. The only thing that I could help is that potentially dispatch request actions from interceptors. This could indeed cause a loop, thats why it is better to use `sendRequest`, like describe in https://github.com/klis87/redux-saga-requests#interceptors-arrow_up

The advantage is that by default this prevents infinite loops like dispatching request action in onSuccess interceptor, because next request would also trigger onSuccess etc. Also, you have ability tochange those defaults like this:
```js
 yield call(sendRequest, action, {
    silent: true,
    runOnRequest: false,
    runOnSuccess: false,
    runOnError: false,
    runOnAbort: false,
});
```

But I am not sure this is the root of your problem

**Comment by klis87** [comment]
Also, if you dont want some requests to be aborted, you can use `action.meta.takeLatest: false`, see docs here https://github.com/klis87/redux-saga-requests#watchrequests

**Comment by spacesuitdiver** [comment]
Yea, I think for my loop scenario I need to somehow have the `onSuccess` interceptor know that this request is the "end of the road" and to instead of firing a token updated action instead fire a token set action. I'm not so sure I want to completely bypass all of the interceptors which is why I keep shying away from using sendRequest manually with those modified options.

**Comment by spacesuitdiver** [comment]
Is it possible to bypass `runOnSuccess` as part of the action payload? Like:
```
{ request: { url: '/yo', runOnSuccess: false } }
```

Just curious.

**Comment by klis87** [comment]
No, it is not possible. And generally using `sendRequest` is recommended in interceptors, because thx to saga context, it provide nice dynamic defaults which prevent loops from happening. 

At some point in some situation blocking interceptor must be blocked, imagine sending request in onError, which would also end up with error, then you will call onError forever and forever dispatch requests. But this depends on situation and use case, those options are adjustable to fit any.

**Comment by spacesuitdiver** [comment]
Also, part of the motivation behind making it fire an action instead of `sendRequest` is so that any feature/duck could subscribe to token update actions firing and perform actions on them.

**Comment by klis87** [comment]
but sendRequest also dispatches actions, even request action with `dispatchRequestAction` as true option, I reccomend reading about interceptors and `sendRequest` docs

**Comment by klis87** [comment]
actually if you dispatch request action, sendRequest is called by watchedRequests anyway :)

**Comment by spacesuitdiver** [comment]
I'll close this for now, I just ended up firing sendRequest. :)
