### ISSUE TITLE
TypeError: Cannot read property 'driver' of undefined

### ISSUE THREAD

**Issue by slaeme** [klis87/redux-saga-requests#255]
Hi, thanks for your library, it is very nice and useful.

I create `RequestInstance` via effect `createRequestInstance` in my app root saga: 
```
...

function* rootSaga() {
    yield createRequestInstance({
        driver: createDriver(axios)
    });

    yield call(watchRequests);
}
```

And `sendRequest` call in in another saga, which runs through `sagaMiddleware.run` after loading a chunk (code-splitting):
```
function* anotherSaga(): Generator<Effect, void, any> {
    yield takeLatest(types.FETCH, sendRequest);
}

sagaMiddleware.run(anotherSaga);
```

When takeLatest call `sendRequest`, the error will be throw:
![image](https://user-images.githubusercontent.com/22623111/59859086-8e667400-9395-11e9-8004-9d34b4389662.png)
because `requestsConfig === undefined` for this "saga instance"
![image](https://user-images.githubusercontent.com/22623111/59859757-cde19000-9396-11e9-8aea-2ce0bb978e39.png)

I'll try describe my case. I request user names with params `userIds: string[]` and if for some `userId` the name have already been loaded, I don’t want to send it to `sendRequest`:
```
function* fetch(action) {
    const userNames = yield select(getUserNames);

    const { userIds } = action.meta;

    const necessaryUserIds = userIds.filter(userId => userTimezoneIds[userId] == null);

    if (!necessaryUserIds.length) {
        return;
    }

    yield call(sendRequest, actions.fetch({ userIds: necessaryUserIds }), {
        dispatchRequestAction: false
    });
}
```

Is this behavior `requestsConfig` normal? 

I solved my problem by filtering the identifiers in the saga, which works earlier than sending the `fetch` action to` redux-request-saga`.

I want to get your opinion on this case. Thanks!

**Comment by klis87** [comment]
I believe this is the problem with redux-saga context, which this library uses. It works like React context. The problem is that `createRequestInstance` creates such context under the hood, which then is read by `sendRequest`. 

The problem is that in order to have access to a context, a saga has to be a child of a ancestor (even grand grand parent) which sets context.

Probably the issues is that your dynamically loaded saga is not treated as child of rootSaga.

You have following possibilities here:
1) give up async saga
2) reorganize async saga so you won't call `sendRequest`, but conditionally `put(actions.fetch({ userIds: necessaryUserIds })`
3) figure out a way to set context in such a way that it could be read by all sagas, even dynamically loaded, maybe there is a way, if not, really it should be added to `redux-saga` as if this is the case, this scenario might be overlooked there
4) define separate `createRequestInstance` in each dynamically loaded saga which needs to use `sendRequest`, we dont have any state there so I think it would be safe to do it to, albeit unconvenient

**Comment by klis87** [comment]
Regarding 3rd point, it might be possible to set initial context https://redux-saga.js.org/docs/api/#createsagamiddlewareoptions 

Intead of `createRequestInstance`, try to pass 
```js
context: {
  REDUX_SAGA_REQUESTS_CONFIG: {
    driver: createDriver(axios),
    onRequest: null,
    onSuccess: null,
    onError: null,
    onAbort: null,
  }
}
```
to `createsagamiddleware`

**Comment by klis87** [comment]
If that works fine, in another realease I will export utility functions to create context as an alternative to `createRequestInstance` for lazy loaded sags

**Comment by slaeme** [comment]
Thanks for the complete answer.

I choose possibility number two and avoided using `sendRequest`.

I think it's early to add utility function to create contex.
Now I know more about context in `redux-saga` and I can use the method `sendRequest` in async saga if need.

If this case is repeated, I will reopen this task.

**Comment by elja** [comment]
Hello there, 

Is there any possible way to implement multiple sagas with `createRequestInstance` and `watchRequests` that will be independent from each other. I have multi-tenant application that have different levels: authentication, administrator, organization level. Each level should have separate `createRequestInstance` with global interceptors. For example `authentication` level saga shouldn't attach any JWT tokens to the request, but administrator and organization level should, moreover organization level should attach current organization id to each request.
