### ISSUE TITLE
Type definition for TypeScript?!

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-saga-requests#288]
Is it planned to create type definitions for **redux-saga-requests** and other packages in this monorepo? 
At the moment I am creating types/interfaces in my project but it would be nice to have them in the package or at least in https://github.com/DefinitelyTyped/DefinitelyTyped. 
I can contribute with my types/interfaces. 
If the type definition is not a priority for this package, in the near future I will work on **@types/redux-saga-requests**

**Comment by klis87** [comment]
@strdr4605 they are already included in `types` directory in each package, for instance https://github.com/klis87/redux-saga-requests/tree/master/packages/redux-saga-requests/types

I guess they are not perfect, we could have more generics too, but I will work on them before releasing 1.0.0. I would also happily accept PR with some fixes for problematic things.

Anyway I think this should wait, as I am working on simplifying this library a lot due to removing `requestsReducer` and sticking only with `networkReducer`, this opened a lot doors for new features and simplicity.
