### ISSUE TITLE
getData for custom reducer ?!

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-saga-requests#294]
I have this action creator 
```ts
const requestGet: (merchantId: string, sessionId: string) => RequestAction = (merchantId: string, sessionId: string): RequestAction => ({
    type: LocationsActionEnum.NEW_API_LOCATIONS_GET_REQUEST,
    payload: {
      request: {
        url: placePickerFacade.getStoreLocations(merchantId, sessionId),
      },
    },
    meta: {
      getData: (_state: RootState, action: AnyAction, _config: MergedReducerConfig): LegacyStoreLocationInterface[] => action.payload.data.value,
    },
  });
```
and following driver
```ts
export interface CustomDriver extends Driver {
  requestInstance: null;
  getAbortSource: () => null;
  abortRequest: () => void;
  sendRequest: (requestConfig: { url: Promise<unknown> }) => Promise<unknown>;
  getSuccessPayload: (response: unknown, request?: unknown) => unknown;
  getErrorPayload: (error: Error) => Error;
}

// TODO: Track https://github.com/klis87/redux-saga-requests/issues/244 for future changes
export const createCustomDriver: () => CustomDriver = (): CustomDriver => ({
  requestInstance: null,
  getAbortSource(): null {
    return null;
  },
  abortRequest(): void {},
  async sendRequest(requestConfig: { url: Promise<unknown> }): Promise<unknown> {
    return requestConfig.url;
  },
  getSuccessPayload(response: unknown): unknown {
    return response;
  },
  getErrorPayload(error: Error): Error {
    return error;
  },
});
```
with custom reducer
```ts
const initialState: LocationsState = {
  visibleStoreLocations: [],
  storeLocations: [],
  pending: 0,
  error: null,
};

export function locationsReducer(state: LocationsState = initialState, action: LocationsActionType): LocationsState {
  if (isActionOf(locationsActions.setVisibleLocations, action)) {
    return { ...state, visibleStoreLocations: action.payload };
  }

  if (LocationsActionEnum.NEW_API_LOCATIONS_GET_REQUEST === action.type) {
    return { ...state, pending: state.pending + 1 };
  }

  if (success(LocationsActionEnum.NEW_API_LOCATIONS_GET_REQUEST) === action.type) {
    return { ...state, storeLocations: action.payload, pending: state.pending - 1 };
  }

  if (error(LocationsActionEnum.NEW_API_LOCATIONS_GET_REQUEST) === action.type) {
    return { ...state, error: action.payload, pending: state.pending - 1 };
  }

  return state;
}
```

**But `getData` does not work for customReducer**
Is this expected??

![Screenshot from 2019-10-08 18-05-49](https://user-images.githubusercontent.com/16056918/66407878-a0c4f600-e9f6-11e9-97e3-b1b75fa73e3a.png)
storeLocations should be a list but it is the object that comes from API and ignore the `getData` from action.meta
![Screenshot from 2019-10-08 18-05-58](https://user-images.githubusercontent.com/16056918/66407890-a4f11380-e9f6-11e9-95f7-bfec3469b04d.png)

**Comment by klis87** [comment]
@strdr4605 yes, for not it is, as getData is called in `networkReducer` and `requestsReducer`

in the future version it will be fixed, as `getData` will be called on saga level in `sendRequest`, so that everything will be consistent, no matter whether u will look at data in `sendRequest` response, dispatch response when using promise middleware, or in custom reducer like in your case

anyway, storing data duplication in customer reducer in my opinion is wrong

state should be never duplicated

I think you use case should be solved with selectors, as it seems you want to duplicate your state instead of computing some values based on state you already have

**Comment by strdr4605** [comment]
@klis87, My team did not really like `networkReducer`, and we decided to move on with custom reducer. In my `networkReducer` will be removed, but I left it just to check if everything works.

**Comment by klis87** [comment]
@strdr4605 this library without networkReducer is a huge lost really, especially in the next version where it will handle caching logic, automatic normalization, easier ssr etc

what dont u like about `networkReducer`, any feedback is appreciated!

if you prefer to stick with custom reducer, just put getData logic into your custom reducer, or use getData in your reducer as action.meta.getData(state, action)

really action.meta.getData in the version you use is to put data transformation data logic in action not in reducer as with networkReducer you just dont write reducers to manage remote data, otherwise it wouldnt be eben part of API

**Comment by klis87** [comment]
Closed, `requestsReducer` as in this topic is not available anymore anyway, everything should be possible with new API anyway, if not, file an issue and I will try to solve it @strdr4605
