### ISSUE TITLE
custom attributes now that customReducer argument from `requestReducer` is removed

### ISSUE THREAD

**Issue by burgalon** [klis87/redux-saga-requests#299]
In one of the recent versions, `requestReducer` removed its second argument of custom reducer. As a result, I'm not sure how can I add a custom global behavior when I want for example to save additional attributes from the response alongside the `pending` and `data`. For example, let's suppose I'd like to save the `requestId` header coming from the response so I can display some debugging data. Or maybe save `lastFetchedAt` attribute... Not sure how this can be done now

**Comment by burgalon** [comment]
p.s: i'm still working in the "old" mode where each FETCH is a requestReducer, and not using the new `mutations` in the actionCreator.... (been wondering if it's an issue of the actionCreator returning a non POJO/simple serializable JSON, but a one with functions.... but that's a separate issue )

**Comment by burgalon** [comment]
it seems like it's possible to pass an `onSuccess` handler for the `requestReducer` however this doesn't seem to apply to the mutations below it. Also ideally, I would like this configuration to be set for all requestReducers like in the older version where you would create an instance of requestReducer with a default config

**Comment by klis87** [comment]
I won't be able to add back custom reducer to `requestsReducer`, as actually future version wont have `requestsReducer` at all, only `networkReducer`. This is because new release will be very huge with simplified API and new features. `networkReducer` allows me to do more because I have all network state within 1 place.

I totally understand though the need to have some local state next to remote state, but actually it doesnt matter where sth is stored in reducers, merging state can be done on selector level. So you can just put your reducer listening to network events and store `requestId` (btw in next releases headers could be optionally stored in reducer by default) and merge it with remote state with `reselect`. In the future version actually built-in selectors will be the only recommended way to get remote data, as state will be less human-readible to support things like better caching and auto normalisation. Also, you can add some attributes with action.meta.getData anyway.

`been wondering if it's an issue of the actionCreator returning a non POJO/simple serializable JSON, but a one with functions.... but that's a separate issue`

no, only reducer state has to be serializable, action doesnt need to be, it doesnt even break Redux time travel, I understand someone might not like it by collocation everything inside action is my goal.

`Also ideally, I would like this configuration to be set for all requestReducers like in the older version where you would create an instance of requestReducer with a default config`

`createRequestsReducer` was removed because you can achieve the same thing with creating your own wrapper around `requestsReducer` and passing to config whatever u want. I dont want to have API which can be done by pure javascript to keep this library simple.

**Comment by burgalon** [comment]
thanks @klis87 !
