### ISSUE TITLE
[fetch-driver-interceptor: onSuccess] should we return Response or body?

### ISSUE THREAD

**Issue by leesiongchan** [klis87/redux-saga-requests#90]
I am trying to use interceptor, but I have discovered that returning `Response` object in `onSuccess` doesn't seem to be useful as I can't `.json` my response as `Response` can only read once. Do you think we should return the `Response body` to `onSuccess` instead?

**Comment by klis87** [comment]
The problem is that the whole response object is really necessery in `onSuccess`, as you might need information like status code, headers etc. So we cannot do this in this library - but you could do this yourself by adjusting fetch driver here https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-fetch/src/fetch-api-driver.js#L40 and using yours in your app.

But maybe you don't need to use `onSuccess` at all, what do you try to do? As there are more ways to adjust success payload globally. If you tell me your use case, I might be able to give u another approach.

**Comment by leesiongchan** [comment]
I am doing some extra dispatch actions when some conditions met, I am currently using `clone` method to clone the response, I don't think is a good idea, probably I will switch to use my own `watcher` instead.

**Comment by klis87** [comment]
Can u give an example? As maybe this is really not to be placed inside interceptor? Interceptors should be used only really for global stuff. What you can do for example is to create new saga:
```js
import { success } from 'redux-saga-requests';

function* waitForASuccess() {
  while (true) {
    const action = yield take(success('SOME_REQUEST');
    // check action.data and dispatch some action here
  }
}

function* rootSaga() {
  yield createRequestInstance(fetch, { driver: fetchDriver });
  yield all([
    watchRequests(),
    fork(waitForASuccess),
  ]);
}
```
In the same way you can add dozens of other sagas, waiting for success, error, abort, request actions of any type/types. Will it solve your use case?

**Comment by leesiongchan** [comment]
Thank you very much, it helps alot.

**Comment by klis87** [comment]
@leesiongchan Since new relese of Fetch driver, you could read `response.data` instead of `response.json()` - https://github.com/klis87/redux-saga-requests/releases/tag/redux-saga-requests-fetch%400.7.0

Writing in case you still need it.
